version: '3.8'

services:
  goodx:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: goodx_app
    shm_size: '8gb'
    volumes:
      - ../../:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - mynetwork

  maildev:
    image: maildev/maildev:latest
    restart: always
    ports:
      - "8085:1080"
      - "8025:1025"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres-data:
  pgadmin-data: